# FileName:    task.c
# Author:      Hung Ka Hing
# UID:         3035782750
# Platform:    Linux
# Description: make 3230shell - compile the 3230 shell

CC = gcc # choose compiler

all: 3230shell_3035782750.c buffer.c linklist.c signals.c task.c buffer.h constant.h linklist.h signals.h task.h
			$(CC) $^ -o 3230shell



